# Generated by Django 3.2.6 on 2021-08-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_no', models.AutoField(db_column='STUDENT_NO', primary_key=True, serialize=False)),
                ('student_name', models.TextField(db_column='STUDENT_NAME')),
                ('student_dob', models.DateField(db_column='STUDENT_DOB')),
                ('student_doj', models.DateField(db_column='STUDENT_DOJ')),
            ],
            options={
                'db_table': 'STUDENT',
                'managed': False,
            },
        ),
    ]
